In [1]:
import numpy as np

# Basic Arithmetic (element-wise)

In [23]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
arr3 = np.arange(21,31)

print(arr1)
print(arr2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]


In [24]:
print("add     : ", arr3 + 10)
print("subtract: ", arr3 - 10)
print("multiply: ", arr3 * 10)
print("divide  : ", arr3 / 10)
print("power   : ", arr3 ^ 10)
print("mod     : ", arr3 % 10)

add     :  [31 32 33 34 35 36 37 38 39 40]
subtract:  [11 12 13 14 15 16 17 18 19 20]
multiply:  [210 220 230 240 250 260 270 280 290 300]
divide  :  [2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]
power   :  [31 28 29 18 19 16 17 22 23 20]
mod     :  [1 2 3 4 5 6 7 8 9 0]


In [25]:
print("\nadd", arr1 + arr2)
print("add", np.add(arr1, arr2))

print("\nsubtract", arr1 - arr2)
print("subtract", np.subtract(arr1, arr2))

print("\nmultiply", arr1 * arr2)
print("multiply", np.multiply(arr1, arr2))

print("\ndivide", arr1 / arr2)
print("divide", np.divide(arr1, arr2))

print("\npower", arr1 ** arr2)
print("power", np.power(arr1, arr2))

print("\nmod", arr1 % arr2)
print("mod", np.mod(arr1, arr2))




add [12 14 16 18 20 22 24 26 28 30]
add [12 14 16 18 20 22 24 26 28 30]

subtract [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
subtract [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]

multiply [ 11  24  39  56  75  96 119 144 171 200]
multiply [ 11  24  39  56  75  96 119 144 171 200]

divide [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
divide [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]

power [                  1                4096             1594323
           268435456         30517578125       2821109907456
     232630513987207   18014398509481984 1350851717672992089
 7766279631452241920]
power [                  1                4096             1594323
           268435456         30517578125       2821109907456
     232630513987207   18014398509481984 1350851717672992089
 7766279631452241920]

mod [ 1  2  3  4  5  6  7  8  9 10]
mod [ 1  2  3  4  5  6  7  8  

# Aggregate Functions (reduce whole array)

In [26]:
arr = np.arange(10)

print("sum   :", np.sum(arr))     # Sum of all elements
print("prod  :", np.prod(arr))    # Product of all elements
print("mean  :", np.mean(arr))    # Mean (average)
print("median:", np.median(arr))  # Median
print("std   :", np.std(arr))     # Standard deviation
print("var   :", np.var(arr))     # Variance
print("min   :", np.min(arr))     # Minimum element
print("max   :", np.max(arr))     # Maximum element
print("argmin:", np.argmin(arr))  # Index of minimum element
print("argmax:", np.argmax(arr))  # Index of maximum element

sum   : 45
prod  : 0
mean  : 4.5
median: 4.5
std   : 2.8722813232690143
var   : 8.25
min   : 0
max   : 9
argmin: 0
argmax: 9


# Exponential and Logarithmic functions

In [30]:
arr = np.arange(1,11)

print("\nexp    :", np.exp(arr))     # e^x for each element
print("\nlog    :", np.log(arr))     # Natural log (ln)
print("\nlog10  :", np.log10(arr))   # Base-10 log
print("\nlog2   :", np.log2(arr))    # Base-2 log


exp    : [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]

log    : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]

log10  : [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]

log2   : [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


# Trigonometric functions

In [51]:
arr = np.arange(1,11)

print("\nsin    :", np.sin(arr))     # Sine
print("\ncos    :", np.cos(arr))     # Cosine
print("\ntan    :", np.tan(arr))     # Tangent
print("\narcsin :", np.arcsin(np.clip(arr/10, -1, 1)))  # Inverse sine (values between -1 and 1)
print("\narccos :", np.arccos(np.clip(arr/10, -1, 1)))  # Inverse cosine
print("\narctan :", np.arctan(arr))  # Inverse tangent


sin    : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]

cos    : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]

tan    : [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]

arcsin : [0.10016742 0.20135792 0.30469265 0.41151685 0.52359878 0.64350111
 0.7753975  0.92729522 1.11976951 1.57079633]

arccos : [1.47062891 1.36943841 1.26610367 1.15927948 1.04719755 0.92729522
 0.79539883 0.64350111 0.45102681 0.        ]

arctan : [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765
 1.42889927 1.44644133 1.46013911 1.47112767]


# Rounding and Flooring

In [58]:
arr = np.array([1.2345, 2.3456, 3.4567])

print("round  :", np.round(arr))    # Round to nearest
print("round  :", np.round(arr, 2)) # Round to 2 decimal places

print("floor  :", np.floor(arr))    # Floor (round down)
print("ceil   :", np.ceil(arr))     # Ceil (round up)

print("trunc  :",np.trunc(arr))    # Truncate (keeps the integer part)
print("rint   :",np.rint(arr))     # Behaves like round(), but outputs float numbers


round  : [1. 2. 3.]
round  : [1.23 2.35 3.46]
floor  : [1. 2. 3.]
ceil   : [2. 3. 4.]
trunc  : [1. 2. 3.]
rint   : [1. 2. 3.]


# Miscellaneous

In [53]:
arr = np.arange(1,11)

print("\nsqrt   :", np.sqrt(arr))       # Square root
print("\nabs    :", np.abs(-arr))       # Absolute value
print("\nclip   :", np.clip(arr, 3, 7)) # Limit values between 3 and 7
print("\ncumsum :", np.cumsum(arr))     # Cumulative sum
print("\ncumprod:", np.cumprod(arr))    # Cumulative product


sqrt   : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

abs    : [ 1  2  3  4  5  6  7  8  9 10]

clip   : [3 3 3 4 5 6 7 7 7 7]

cumsum : [ 1  3  6 10 15 21 28 36 45 55]

cumprod: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
