In [4]:
import numpy as np

# Array indexing

In [9]:
arr = np.array([1, 2, 3, 4, 5])

# access numpy elements
print(arr[0])    # 1
print(arr[1])    # 2
print(arr[2])    # 3
print(arr[3])    # 4
print(arr[4])    # 5

# using negative indexing
print(arr[-1])    # 5
print(arr[-2])    # 4
print(arr[-3])    # 3
print(arr[-4])    # 2
print(arr[-5])    # 1

# select elements at index multiple indices like at 1, 3, 0
print(arr[[1, 3, 0]])

1
2
3
4
5
5
4
3
2
1
[2 4 1]


# Fancy indexing

In [ ]:
# arr[start:end:step]
# start is default to 0
# end is default to array's end (excluded)
# step is optional default to 1

numbers = np.arange(10)  # 0-9

# access the first 3 elements
nums1 = numbers[:3]

# access the elements except first 3 elements
nums2 = numbers[3:]

# access the last 3 elements
nums3 = numbers[-3:]

# access the elements except last 3 elements
nums4 = numbers[:-3]

# access the elemensts between first 3 and last 3
nums5 = numbers[3:-3]

# access every elements at odd indices
nums6 = numbers[1::2]  # start is 1 and step is 2

# access every elements at even indices
nums7 = numbers[::2]  # start is 0 and step is 2

# access elements from start to end without using any number
nums8 = numbers[:]

# access the elements in reverse order
nums9 = numbers[::-1]  # setp is -1 so, it reads backward

print("nums1: ",nums1)
print("nums2: ",nums2)
print("nums3: ",nums3)
print("nums4: ",nums4)
print("nums5: ",nums5)
print("nums6: ",nums6)
print("nums7: ",nums7)
print("nums8: ",nums8)
print("nums9: ",nums9)

nums1:  [0 1 2]
nums2:  [3 4 5 6 7 8 9]
nums3:  [7 8 9]
nums4:  [0 1 2 3 4 5 6]
nums5:  [3 4 5 6]
nums6:  [1 3 5 7 9]
nums7:  [0 2 4 6 8]
nums8:  [0 1 2 3 4 5 6 7 8 9]
nums9:  [9 8 7 6 5 4 3 2 1 0]


# Boolean indexing

In [ ]:
numbers = np.arange(10) # 0-9

# select only the even numbers from the array
even_numbers = numbers[numbers % 2 == 0]

# select only the odd numbers from the array
odd_numbers = numbers[numbers % 2 != 0]

# select only the numbers which are greater then 6
large_numbers = numbers[numbers > 6]

print(even_numbers)
print(odd_numbers)
print(large_numbers)

# actually 'numbers > 6' creates a boolean mask which can be used to select numbers for which it is true
print(numbers > 6)

[0 2 4 6 8]
[1 3 5 7 9]
[7 8 9]
[False False False False False False False  True  True  True]


# Modifying elements

In [ ]:
numbers = np.arange(10)

# set element at 4th index to 88 
numbers[4] = 88
print(numbers)

# set elements at indices 3,5,6 to 99
numbers[[2,5,6]] = 99
print(numbers)

# set every elements at even indices to 0
numbers[::2] = 0
print(numbers)

# set every elements at odd indices to 11
numbers[1::2] = 11
print(numbers)

# set every elements greater then 8 to 98
numbers[numbers > 8] = 98
print(numbers)

# set every elements which are 0 to 10
numbers[numbers == 0] = 10
print(numbers)

[ 0  1  2  3 88  5  6  7  8  9]
[ 0  1 99  3 88 99 99  7  8  9]
[ 0  1  0  3  0 99  0  7  0  9]
[ 0 11  0 11  0 11  0 11  0 11]
[ 0 98  0 98  0 98  0 98  0 98]
[10 98 10 98 10 98 10 98 10 98]
