In [ ]:
import numpy as np

# Array Creation

In [ ]:
# create numpy array using the numbers list
arr = np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

In [ ]:
# create an empty array with total capacity of 6
empty_array = np.empty(6)
empty_array

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323])

In [ ]:
# create an array with 5 elements filled with zeros
arr = np.zeros(5)
arr

array([1., 1., 1., 1., 1.])

In [7]:
# create an array with 5 elements filled with ones
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [ ]:
# np.arange(start, stop, size)
# Default values
# start- the start value, 0 by default
# stop - exclusive
# (optional) size is 1. 

# create an array with values from 0 to 5
array1 = np.arange(6)
print(array1)

# create an array with values from 3 to 9 with a size of 2
array2 = np.arange(3, 10, 2)
print(array2)

[0 1 2 3 4 5]
[3 5 7 9]


In [ ]:
# np.linspace(start, stop, nums)
# start- the start value, 0 by default
# stop- the end value of the sequence (inclusive)
# nums(optional)- number of elements to generate (int)

# create an array with 4 elements between 1 and 10
array1 = np.linspace(1, 10, 4)
array1

array([ 1.,  4.,  7., 10.])

In [15]:
# elements between 10 and 50 with stepsize 4
array1 = np.arange(10, 50 , 4)
print(array1)

# generate 4 elements between 10 and 50 
array2 = np.linspace(10, 50 , 4)
print(array2)

[10 14 18 22 26 30 34 38 42 46]
[10.         23.33333333 36.66666667 50.        ]


In [23]:
# random number between 1 and 100
random_number = np.random.randint(1, 100)
print(random_number)

# array of length 5 with random integer values ranging from 1 to 100 both inclusive
rand_array = np.random.randint(1, 100, size=5)
print(rand_array)

# generate an array of 4 random numbers between 0 and 1
array1 = np.random.rand(4)
print(array1)

25
[20 86 30 20 90]
[0.31565938 0.98925155 0.16937249 0.61642123]
