# N-d Array

In [3]:
import numpy as np

In [4]:
# create 1D array
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# create 2D array
array2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# create 3D array
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# create a 3D array with 2 "matrices" of 3 rows and 4 columns each
np_array = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)

print(np_array, "\n")

print(array1, "\n")
print(array2, "\n")
print(array3, "\n")
print(np_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 

[1 2 3 4 5 6 7 8] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
# create an empty 2-D array with 3 rows and 4 columns
empty2d_np_array = np.empty((3, 4))

# create an empty 3-D array with 2 matrices, 3 rows and 4 columns
empty3d_np_array = np.empty((2, 3, 4))

# create a 2x3 array filled with 0s
zeros_np_array = np.zeros((2, 3))

# create a 3x3x3 array filled with 1s
ones_np_array = np.ones((3, 3, 3))

# create 2x2 array all filled with the value 5
filled_np_array = np.full((2, 2), 5)

print(empty2d_np_array, "\n")
print(empty3d_np_array, "\n")
print(zeros_np_array, "\n")
print(ones_np_array, "\n")
print(filled_np_array, "\n")

[[9.61893831e-312 2.86558075e-322 0.00000000e+000 0.00000000e+000]
 [4.24512503e+175 1.58817677e-052 7.42142791e-091 7.24744760e+169]
 [8.26993545e-072 3.30524533e+179 6.48224659e+170 5.82471487e+257]] 

[[[6.23042070e-307 1.29060531e-306 1.11260755e-306 1.24606309e-306]
  [1.33512173e-306 6.23055651e-307 1.06810268e-306 6.89807188e-307]
  [1.60218491e-306 1.02360867e-306 1.33511290e-306 1.11258854e-306]]

 [[1.11261502e-306 1.42410839e-306 7.56597770e-307 6.23059726e-307]
  [1.42419530e-306 1.78018811e-306 1.33511562e-306 1.33510882e-306]
  [9.34609790e-307 9.34609111e-307 1.33511290e-306 1.42410974e-306]]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 

[[5 5]
 [5 5]] 



# Reshaping

In [61]:
# numpy.reshape(array, shape, order)

# array - an original array
# shape - desired new shape of the array
# order (optional) - specifies the order in which the array elements are reshaped.
# default order = 'C' elements are stored row-wise
#         order = 'F' elements are stored column-wise

# create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# reshape the array into a 2x4 array with 'C' order
result1 = np.reshape(arr1d, (2, 4), order="C")
print("New array with 'C' order:\n", result1)

# reshape the array into a 2x4 array with 'F' order
result2 = np.reshape(arr1d, (2, 4), order="F")
print("\nNew array with 'F' order:\n", result2)

# reshape a 1D array into a 3D array
# with 2 matrices, 2 rows and 2 cols
arr3d = np.reshape(arr1d, (2, 2, 2))
print("\n3d array:\n", arr3d)

# reshape the array with -1 for the second dimension
result = np.reshape(arr1d, (2, -1))
# we have limited the number of rows to 2 and left the number of columns open.
print(result)

arr1 = np.arange(1, 10).reshape((3, 3))  # 2d array with 3 rows and 3 cols
print(arr1)

# indexing
print(arr1[1, 2])  # Output: 6

arr2 = np.arange(1, 9).reshape((2, 2, 2))  # 3d array with 2 matrices, 2 rows and 2 cols
print(arr2)

# indexing
print(arr2[(1, 1, 1)])  # output 8

New array with 'C' order:
 [[1 2 3 4]
 [5 6 7 8]]

New array with 'F' order:
 [[1 3 5 7]
 [2 4 6 8]]

3d array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


# flatten

In [ ]:
# Multi dimensional arrays can be converted to 1D arrays by collapsing other dimensions into one.
# This is called array flattening.

array1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# flatten the array using -1 as second argument of reshape
reshaped_array = np.reshape(array1, -1)
print("Reshape:", reshaped_array)

# flatten the array row-wise
# default oder = 'C'
result1 = array1.flatten()
print("C:", result1)

# flatten the array column-wise
result2 = array1.flatten(order="F")
print("F:", result2)

# if order = 'A', it will preserve the array's 'C' or 'F' ordering:

# flatten the array
result3 = np.ravel(array1)
print("Ravel: ", result3)

# difference between flatten and ravel

# flatten is used as an array object
array2 = array1.flatten()
print(array2)

# ravel is used as a library function
array3 = np.ravel(array1)
print(array3)

# flatten() always returns a copy of the original array. if you modify copy it won't affect original array
# whereas ravel() returns the view of the array. if you modify view it will affect original array

# flatten cannot be used with lists, it only works with arrays
# ravel can work with both

Reshape: [0 1 2 3 4 5 6 7]
C: [0 1 2 3 4 5 6 7]
F: [0 4 1 5 2 6 3 7]
Ravel:  [0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


# Slicing

In [ ]:
# for 2d
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[:,:]) # all rows and all coulmns

print("\n")

print(arr[:2, :])  # 1st, 2nd row and all columns
# Output: [[1 2 3] [4 5 6]] 

print("\n")

print(np_array[:, 1:3])  # all rows and 2nd, 3rd columns 
# Output: [[2 3] [5 6] [8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]


[[[ 5  6  7  8]
  [ 9 10 11 12]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [24]:
# for 3d
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("entire array:\n", arr[:, :, :])

print("\n")

print("from second matrix select all rows and all columns:\n", arr[1, :, :]) 

print("\n")

print("from all matrices select second row and all columns:\n", arr[:, 1, :])  

print("\n")

print("from all matrices select all rows and second column:\n", arr[:,:,1])


entire array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


from second matrix select all rows and all columns:
 [[5 6]
 [7 8]]


from all matrices select second row and all columns:
 [[3 4]
 [7 8]]


from all matrices select all rows and second column:
 [[2 4]
 [6 8]]


# Modifying

In [ ]:
# for 2d
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, "\n")

# change the value of element in second row and third column to 10
arr[1, 2] = 10

print(arr, "\n")

# change the value of all elements in second row to 10
arr[1, :] = 10

print(arr, "\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]] 

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]] 



In [78]:
# for 3d

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr, "\n\n")

arr[0, 1, 1] = 10
print("change the value of element in first matrix, 2nd row and 2nd column to 10:\n",arr, "\n")

arr[1, 1, :] = 20
print("change the value of all elements in second matrix, second row to 20:\n",arr, "\n")

arr[1, :, :] = 11
print("change the value of all elements in second matrix to 11:\n",arr, "\n")

arr[:, :, 1] = 9
print("change the value of elements from all matrices, from all rows and 2nd column to 9:\n",arr, "\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 


change the value of element in first matrix, 2nd row and 2nd column to 10:
 [[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [ 7  8]]] 

change the value of all elements in second matrix, second row to 20:
 [[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [20 20]]] 

change the value of all elements in second matrix to 11:
 [[[ 1  2]
  [ 3 10]]

 [[11 11]
  [11 11]]] 

change the value of elements from all matrices, from all rows and 2nd column to 9:
 [[[ 1  9]
  [ 3  9]]

 [[11  9]
  [11  9]]] 

